# Generated by Django 5.1.7 on 2025-03-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('altura', models.FloatField(help_text='Altura em metros')),
                ('peso', models.FloatField(help_text='Peso em kg')),
                ('percentual_gordura', models.FloatField(verbose_name='% Gordura')),
                ('massa_magra', models.FloatField()),
                ('gordura_visceral', models.IntegerField()),
                ('tmb', models.IntegerField(verbose_name='Taxa Metabólica Basal')),
                ('idade_metabolica', models.IntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao.paciente')),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
