# Generated by Django 5.1.7 on 2025-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_avaliacao_abdominal_avaliacao_axilar_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='protocolo',
            field=models.CharField(choices=[('POLLOCK_7', 'Pollock 7 Dobras'), ('FALKNER_4', 'Falkner 4 Dobras')], default='POLLOCK_7', max_length=10),
        ),
    ]
