# Generated by Django 5.2 on 2025-04-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_avaliacao_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='abdomen',
            field=models.FloatField(blank=True, null=True, verbose_name='Abdômen (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='antebraco_direito',
            field=models.FloatField(blank=True, null=True, verbose_name='Antebraço Direito (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='antebraco_esquerdo',
            field=models.FloatField(blank=True, null=True, verbose_name='Antebraço Esquerdo (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='braco_direito',
            field=models.FloatField(blank=True, null=True, verbose_name='Braço Direito (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='braco_esquerdo',
            field=models.FloatField(blank=True, null=True, verbose_name='Braço Esquerdo (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='cintura',
            field=models.FloatField(blank=True, null=True, verbose_name='Cintura (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='coxa_direita',
            field=models.FloatField(blank=True, null=True, verbose_name='Coxa Direita (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='coxa_esquerda',
            field=models.FloatField(blank=True, null=True, verbose_name='Coxa Esquerda (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='panturrilha_direita',
            field=models.FloatField(blank=True, null=True, verbose_name='Panturrilha Direita (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='panturrilha_esquerda',
            field=models.FloatField(blank=True, null=True, verbose_name='Panturrilha Esquerda (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='quadril',
            field=models.FloatField(blank=True, null=True, verbose_name='Quadril (mm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tronco',
            field=models.FloatField(blank=True, null=True, verbose_name='Tronco (mm)'),
        ),
    ]
