# Generated by Django 5.2 on 2025-05-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_avaliacao_abdomen_avaliacao_antebraco_direito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(),
        ),
    ]
